// Export Handler
class ExportHandler {
    constructor() {
        this.labelElement = null;
    }

    // Set the label element to export
    setLabelElement(element) {
        this.labelElement = element;
    }

    // Export as PNG
    async exportPNG() {
        if (!this.labelElement) {
            throw new Error('No label element set for export');
        }

        try {
            // Use html2canvas to convert the element to canvas
            const canvas = await html2canvas(this.labelElement, {
                backgroundColor: '#ffffff',
                scale: 2, // Higher resolution
                useCORS: true,
                allowTaint: true,
                width: 350,
                height: null,
                scrollX: 0,
                scrollY: 0
            });

            // Convert canvas to blob
            return new Promise((resolve) => {
                canvas.toBlob((blob) => {
                    const url = URL.createObjectURL(blob);
                    this.downloadFile(url, 'nutrition-label.png');
                    resolve(url);
                }, 'image/png', 1.0);
            });
        } catch (error) {
            console.error('Error generating PNG:', error);
            throw error;
        }
    }

    // Export as PDF
    async exportPDF() {
        if (!this.labelElement) {
            throw new Error('No label element set for export');
        }

        try {
            // First convert to canvas
            const canvas = await html2canvas(this.labelElement, {
                backgroundColor: '#ffffff',
                scale: 2,
                useCORS: true,
                allowTaint: true,
                width: 350,
                height: null
            });

            // Create PDF using jsPDF
            const { jsPDF } = window.jspdf;
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4'
            });

            // Calculate dimensions
            const imgWidth = 100; // mm
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            // Add image to PDF
            const imgData = canvas.toDataURL('image/png');
            pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);

            // Save PDF
            pdf.save('nutrition-label.pdf');
        } catch (error) {
            console.error('Error generating PDF:', error);
            throw error;
        }
    }

    // Generate embed code
    generateEmbedCode() {
        if (!this.labelElement) {
            throw new Error('No label element set for export');
        }

        const labelHTML = this.labelElement.outerHTML;
        
        // Create complete embed code with styles
        const embedCode = `<!-- FDA Nutrition Label - Generated by NutriJewel -->
<style>
/* FDA Nutrition Label Styles */
.nutrition-facts {
    width: 350px;
    margin: 0 auto;
    background: white;
    border: 2px solid #000;
    font-family: Arial, sans-serif;
    font-size: 11px;
    line-height: 1.2;
    color: #000;
    padding: 5px;
}

.nutrition-title {
    font-size: 24px;
    font-weight: bold;
    text-align: left;
    margin-bottom: 2px;
    letter-spacing: 0.5px;
}

.serving-info {
    border-bottom: 8px solid #000;
    padding-bottom: 2px;
    margin-bottom: 2px;
}

.servings-per-container {
    font-size: 11px;
    margin-bottom: 1px;
}

.serving-size {
    font-size: 11px;
}

.calories-section {
    border-bottom: 4px solid #000;
    padding: 2px 0;
    margin-bottom: 2px;
}

.calories {
    font-size: 16px;
    display: flex;
    justify-content: space-between;
    align-items: baseline;
}

.calories-value {
    font-size: 24px;
    font-weight: bold;
}

.daily-value-note {
    font-size: 10px;
    text-align: right;
    border-bottom: 1px solid #000;
    padding-bottom: 1px;
    margin-bottom: 1px;
    font-weight: bold;
}

.nutrients {
    border-bottom: 4px solid #000;
    margin-bottom: 2px;
}

.nutrient-row {
    display: flex;
    justify-content: space-between;
    padding: 1px 0;
    font-size: 11px;
    border-bottom: 1px solid #000;
}

.nutrient-row:last-child {
    border-bottom: none;
}

.nutrient-row.major {
    font-weight: bold;
}

.nutrient-row.indent {
    padding-left: 15px;
}

.nutrient-row.double-indent {
    padding-left: 30px;
    font-style: italic;
}

.nutrient-name {
    flex: 1;
}

.nutrient-amount {
    margin-right: 10px;
    min-width: 30px;
    text-align: right;
}

.daily-value {
    min-width: 30px;
    text-align: right;
    font-weight: bold;
}

.vitamins-minerals {
    margin-bottom: 3px;
}

.vitamins-minerals .nutrient-row {
    border-bottom: none;
    font-size: 10px;
}

.daily-value-footnote {
    font-size: 9px;
    border-top: 1px solid #000;
    padding-top: 2px;
    line-height: 1.1;
}
</style>

${labelHTML}`;

        return embedCode;
    }

    // Download file helper
    downloadFile(url, filename) {
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        
        // Clean up the URL object
        setTimeout(() => URL.revokeObjectURL(url), 100);
    }

    // Copy text to clipboard
    async copyToClipboard(text) {
        try {
            await navigator.clipboard.writeText(text);
            return true;
        } catch (error) {
            // Fallback for older browsers
            const textArea = document.createElement('textarea');
            textArea.value = text;
            textArea.style.position = 'fixed';
            textArea.style.top = '-1000px';
            document.body.appendChild(textArea);
            textArea.select();
            
            try {
                document.execCommand('copy');
                return true;
            } catch (err) {
                console.error('Copy failed:', err);
                return false;
            } finally {
                document.body.removeChild(textArea);
            }
        }
    }
}

// Global export handler instance
window.exportHandler = new ExportHandler();
